name: curve-leverage-bot-vyper

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry